/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c4afd07741f259355be84c1dfc5f123d)
interface __BaseEnv_Env {
	VibecoderStore: KVNamespace;
	TEMPLATES_BUCKET: R2Bucket;
	DB: D1Database;
	DISPATCHER: DispatchNamespace;
	LOADER: WorkerLoader;
	BROWSER: BrowserRun;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
	ALLOWED_EMAIL: "";
	DISPATCH_NAMESPACE: "erpeos-default-namespace";
	ENABLE_READ_REPLICAS: "true";
	CLOUDFLARE_AI_GATEWAY: "aire-gateway";
	PLATFORM_CAPABILITIES: {"features":{"app":{"enabled":true},"presentation":{"enabled":false},"general":{"enabled":false}},"version":"1.0.0"};
	MAX_SANDBOX_INSTANCES: "10";
	SANDBOX_INSTANCE_TYPE: "standard-3";
	DEV_BROWSER_SIDECAR_URL: "http://127.0.0.1:9223";
	DEV_BROWSER_PREVIEW_ORIGIN: "http://localhost:5173";
	GOOGLE_AI_STUDIO_API_KEY: string;
	JWT_SECRET: string;
	WEBHOOK_SECRET: string;
	SECRETS_ENCRYPTION_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_EXPORTER_CLIENT_ID: string;
	GITHUB_EXPORTER_CLIENT_SECRET: string;
	CLOUDFLARE_OAUTH_CLIENT_ID: string;
	CLOUDFLARE_OAUTH_CLIENT_SECRET: string;
	CLOUDFLARE_OAUTH_AUTH_URL: string;
	CLOUDFLARE_OAUTH_TOKEN_URL: string;
	CLOUDFLARE_OAUTH_USERINFO_URL: string;
	CLOUDFLARE_OAUTH_SCOPES: string;
	CF_OAUTH_ENCRYPTION_KEY: string;
	ENABLE_CLOUDFLARE_LIMITS: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_AI_GATEWAY_TOKEN: string;
	CLOUDFLARE_AI_GATEWAY_URL: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENROUTER_API_KEY: string;
	GROQ_API_KEY: string;
	SERPAPI_KEY: string;
	PLATFORM_MODEL_PROVIDERS: string;
	AI_PROXY_JWT_SECRET: string;
	SENTRY_DSN: string;
	CF_ACCESS_ID: string;
	CF_ACCESS_SECRET: string;
	SANDBOX_SERVICE_API_KEY: string;
	SANDBOX_SERVICE_TYPE: string;
	SANDBOX_SERVICE_URL: string;
	DAYTONA_API_KEY: string;
	DAYTONA_API_URL: string;
	DAYTONA_TARGET: string;
	DAYTONA_AUTO_STOP_INTERVAL: string;
	DAYTONA_AUTO_DELETE_INTERVAL: string;
	DAYTONA_PREVIEW_URL_TTL_SECONDS: string;
	ALLOCATION_STRATEGY: string;
	USE_CLOUDFLARE_IMAGES: string;
	EXTERNAL_AI_GATEWAY_URL: string;
	EXTERNAL_AI_GATEWAY_API_KEY: string;
	EXTERNAL_AI_GATEWAY_MODEL: string;
	CUSTOM_DOMAIN: string;
	CUSTOM_PREVIEW_DOMAIN: string;
	ENVIRONMENT: string;
	USE_TUNNEL_FOR_PREVIEW: string;
	CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
	Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
	DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
	UserSecretsStore: DurableObjectNamespace<import("./worker/index").UserSecretsStore>;
	THINK_DO: DurableObjectNamespace<import("./worker/index").ThinkAgent>;
	SPACE_DO: DurableObjectNamespace<import("./worker/index").SpaceDO>;
	API_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "UserSecretsStore" | "SpaceDO" | "ThinkAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "PLATFORM_CAPABILITIES" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "DEV_BROWSER_SIDECAR_URL" | "DEV_BROWSER_PREVIEW_ORIGIN" | "GOOGLE_AI_STUDIO_API_KEY" | "JWT_SECRET" | "WEBHOOK_SECRET" | "SECRETS_ENCRYPTION_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_EXPORTER_CLIENT_ID" | "GITHUB_EXPORTER_CLIENT_SECRET" | "CLOUDFLARE_OAUTH_CLIENT_ID" | "CLOUDFLARE_OAUTH_CLIENT_SECRET" | "CLOUDFLARE_OAUTH_AUTH_URL" | "CLOUDFLARE_OAUTH_TOKEN_URL" | "CLOUDFLARE_OAUTH_USERINFO_URL" | "CLOUDFLARE_OAUTH_SCOPES" | "CF_OAUTH_ENCRYPTION_KEY" | "ENABLE_CLOUDFLARE_LIMITS" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "CLOUDFLARE_AI_GATEWAY_URL" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENROUTER_API_KEY" | "GROQ_API_KEY" | "SERPAPI_KEY" | "PLATFORM_MODEL_PROVIDERS" | "AI_PROXY_JWT_SECRET" | "SENTRY_DSN" | "CF_ACCESS_ID" | "CF_ACCESS_SECRET" | "SANDBOX_SERVICE_API_KEY" | "SANDBOX_SERVICE_TYPE" | "SANDBOX_SERVICE_URL" | "DAYTONA_API_KEY" | "DAYTONA_API_URL" | "DAYTONA_TARGET" | "DAYTONA_AUTO_STOP_INTERVAL" | "DAYTONA_AUTO_DELETE_INTERVAL" | "DAYTONA_PREVIEW_URL_TTL_SECONDS" | "ALLOCATION_STRATEGY" | "USE_CLOUDFLARE_IMAGES" | "EXTERNAL_AI_GATEWAY_URL" | "EXTERNAL_AI_GATEWAY_API_KEY" | "EXTERNAL_AI_GATEWAY_MODEL" | "CUSTOM_DOMAIN" | "CUSTOM_PREVIEW_DOMAIN" | "ENVIRONMENT" | "USE_TUNNEL_FOR_PREVIEW">> {}
}
declare module "*.md" {
	const value: string;
	export default value;
}
declare module "*.md?raw" {
	const value: string;
	export default value;
}
